services:
  - type: web
    name: earnings-analyser
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."
    startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
